name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create DB directory
        run: mkdir -p db

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Create auth directory
        run: mkdir -p playwright/.auth

      - name: Initialize database
        run: npm run init:db

      - name: Run tests
        run: |
          # Use the webServer option in playwright.config.js to start the server
          npm test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
