name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Create DB directory
        run: mkdir -p db

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Create auth directory
        run: mkdir -p playwright/.auth

      - name: Initialize database
        run: npm run init:db

      - name: Start server and run tests
        run: |
          # Start the server in the background
          npm start &
          # Save the process ID
          SERVER_PID=$!
          # Wait for the server to start
          echo "Waiting for server to start..."
          sleep 5
          # Check if the server is running
          if curl -s http://localhost:3000 > /dev/null; then
            echo "Server is running"
          else
            echo "Server failed to start"
            exit 1
          fi
          # Run the tests
          npm test
          # Kill the server process
          kill $SERVER_PID

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
